# Generated by Django 2.2.7 on 2019-12-01 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_root', models.URLField(max_length=100, verbose_name='初始地址')),
                ('url_goal', models.URLField(max_length=500, verbose_name='最终的爬取地址')),
                ('spider_message', models.TextField(max_length=500)),
                ('html_message', models.TextField(max_length=500)),
                ('gmt_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaggageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=3, verbose_name='出发地')),
                ('destinent', models.CharField(max_length=3, verbose_name='抵达地')),
                ('baggage_message', models.TextField(max_length=500)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Message')),
            ],
        ),
    ]
